const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#1B8A3C",
    background: "#F7FAF8",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#1B8A3C",
    primaryForeground: "#FFFFFF",
    secondary: "#EAF5EE",
    secondaryForeground: "#1B8A3C",
    muted: "#F0F0EC",
    mutedForeground: "#6B7280",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E3EDE5",
    input: "#E3EDE5",
    farmerColor: "#1B8A3C",
    consumerColor: "#2563EB",
    riderColor: "#7C3AED",
    freshGreen: "#15803D",
    freshGreenBg: "#DCFCE7",
    warningText: "#B45309",
    warningBg: "#FEF3C7",
    dangerText: "#B91C1C",
    dangerBg: "#FEE2E2",
    starColor: "#F59E0B",
  },
  radius: 14,
};

export default colors;
